# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/request.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import protos.utils_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/request.proto',
  package='crypto',
  serialized_pb=_b('\n\x14protos/request.proto\x12\x06\x63rypto\x1a\x12protos/utils.proto\"\x81\x01\n\x07Request\x12\x1d\n\x06qubits\x18\x01 \x03(\x0e\x32\r.crypto.Qubit\x12\x1b\n\x05gates\x18\x02 \x03(\x0e\x32\x0c.crypto.Gate\x12\x1e\n\x06option\x18\x03 \x01(\x0b\x32\x0e.crypto.Option\x12\x1a\n\x04\x61lgo\x18\x04 \x02(\x0e\x32\x0c.crypto.Algo')
  ,
  dependencies=[protos.utils_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='crypto.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='qubits', full_name='crypto.Request.qubits', index=0,
      number=1, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gates', full_name='crypto.Request.gates', index=1,
      number=2, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='option', full_name='crypto.Request.option', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='algo', full_name='crypto.Request.algo', index=3,
      number=4, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=182,
)

_REQUEST.fields_by_name['qubits'].enum_type = protos.utils_pb2._QUBIT
_REQUEST.fields_by_name['gates'].enum_type = protos.utils_pb2._GATE
_REQUEST.fields_by_name['option'].message_type = protos.utils_pb2._OPTION
_REQUEST.fields_by_name['algo'].enum_type = protos.utils_pb2._ALGO
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'protos.request_pb2'
  # @@protoc_insertion_point(class_scope:crypto.Request)
  ))
_sym_db.RegisterMessage(Request)


# @@protoc_insertion_point(module_scope)
