# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/utils.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/utils.proto',
  package='crypto',
  serialized_pb=_b('\n\x12protos/utils.proto\x12\x06\x63rypto\"$\n\x05Qubit\x12\x0c\n\x04real\x18\x01 \x02(\x02\x12\r\n\x05image\x18\x02 \x02(\x02\"\x12\n\x06Option*\x08\x08\n\x10\x80\x80\x80\x80\x02*\x1b\n\x04Gate\x12\x08\n\x04PLUS\x10\x00\x12\t\n\x05\x43ROSS\x10\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_GATE = _descriptor.EnumDescriptor(
  name='Gate',
  full_name='crypto.Gate',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PLUS', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CROSS', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=88,
  serialized_end=115,
)
_sym_db.RegisterEnumDescriptor(_GATE)

Gate = enum_type_wrapper.EnumTypeWrapper(_GATE)
PLUS = 0
CROSS = 1



_QUBIT = _descriptor.Descriptor(
  name='Qubit',
  full_name='crypto.Qubit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='real', full_name='crypto.Qubit.real', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='image', full_name='crypto.Qubit.image', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=66,
)


_OPTION = _descriptor.Descriptor(
  name='Option',
  full_name='crypto.Option',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=True,
  extension_ranges=[(10, 536870912), ],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=86,
)

DESCRIPTOR.message_types_by_name['Qubit'] = _QUBIT
DESCRIPTOR.message_types_by_name['Option'] = _OPTION
DESCRIPTOR.enum_types_by_name['Gate'] = _GATE

Qubit = _reflection.GeneratedProtocolMessageType('Qubit', (_message.Message,), dict(
  DESCRIPTOR = _QUBIT,
  __module__ = 'protos.utils_pb2'
  # @@protoc_insertion_point(class_scope:crypto.Qubit)
  ))
_sym_db.RegisterMessage(Qubit)

Option = _reflection.GeneratedProtocolMessageType('Option', (_message.Message,), dict(
  DESCRIPTOR = _OPTION,
  __module__ = 'protos.utils_pb2'
  # @@protoc_insertion_point(class_scope:crypto.Option)
  ))
_sym_db.RegisterMessage(Option)


# @@protoc_insertion_point(module_scope)
