# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/set_msg.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import protos.utils_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/set_msg.proto',
  package='crypto',
  serialized_pb=_b('\n\x14protos/set_msg.proto\x12\x06\x63rypto\x1a\x12protos/utils.proto\"+\n\rSetMsgRequest\x12\r\n\x05login\x18\x01 \x02(\x0c\x12\x0b\n\x03msg\x18\x02 \x02(\x0c\"\x1d\n\x0eSetMsgResponse\x12\x0b\n\x03msg\x18\x01 \x02(\x0c:>\n\x0fSET_MSG_REQUEST\x12\x0e.crypto.Option\x18\x0b \x01(\x0b\x32\x15.crypto.SetMsgRequest:@\n\x10SET_MSG_RESPONSE\x12\x0e.crypto.Option\x18\x0c \x01(\x0b\x32\x16.crypto.SetMsgResponse')
  ,
  dependencies=[protos.utils_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


SET_MSG_REQUEST_FIELD_NUMBER = 11
SET_MSG_REQUEST = _descriptor.FieldDescriptor(
  name='SET_MSG_REQUEST', full_name='crypto.SET_MSG_REQUEST', index=0,
  number=11, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
SET_MSG_RESPONSE_FIELD_NUMBER = 12
SET_MSG_RESPONSE = _descriptor.FieldDescriptor(
  name='SET_MSG_RESPONSE', full_name='crypto.SET_MSG_RESPONSE', index=1,
  number=12, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


_SETMSGREQUEST = _descriptor.Descriptor(
  name='SetMsgRequest',
  full_name='crypto.SetMsgRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='login', full_name='crypto.SetMsgRequest.login', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='msg', full_name='crypto.SetMsgRequest.msg', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=95,
)


_SETMSGRESPONSE = _descriptor.Descriptor(
  name='SetMsgResponse',
  full_name='crypto.SetMsgResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='crypto.SetMsgResponse.msg', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=126,
)

DESCRIPTOR.message_types_by_name['SetMsgRequest'] = _SETMSGREQUEST
DESCRIPTOR.message_types_by_name['SetMsgResponse'] = _SETMSGRESPONSE
DESCRIPTOR.extensions_by_name['SET_MSG_REQUEST'] = SET_MSG_REQUEST
DESCRIPTOR.extensions_by_name['SET_MSG_RESPONSE'] = SET_MSG_RESPONSE

SetMsgRequest = _reflection.GeneratedProtocolMessageType('SetMsgRequest', (_message.Message,), dict(
  DESCRIPTOR = _SETMSGREQUEST,
  __module__ = 'protos.set_msg_pb2'
  # @@protoc_insertion_point(class_scope:crypto.SetMsgRequest)
  ))
_sym_db.RegisterMessage(SetMsgRequest)

SetMsgResponse = _reflection.GeneratedProtocolMessageType('SetMsgResponse', (_message.Message,), dict(
  DESCRIPTOR = _SETMSGRESPONSE,
  __module__ = 'protos.set_msg_pb2'
  # @@protoc_insertion_point(class_scope:crypto.SetMsgResponse)
  ))
_sym_db.RegisterMessage(SetMsgResponse)

SET_MSG_REQUEST.message_type = _SETMSGREQUEST
protos.utils_pb2.Option.RegisterExtension(SET_MSG_REQUEST)
SET_MSG_RESPONSE.message_type = _SETMSGRESPONSE
protos.utils_pb2.Option.RegisterExtension(SET_MSG_RESPONSE)

# @@protoc_insertion_point(module_scope)
