FROM mcr.microsoft.com/dotnet/core/sdk:3.0

RUN apt-get update -yq && \
    apt-get install curl -yq 
RUN curl -sL https://deb.nodesource.com/setup_12.x | bash -

RUN apt-get install -y nodejs

COPY ./src/ClientApp/*.json /app/ClientApp/
WORKDIR /app/ClientApp
RUN npm install

COPY ./src /app

CMD ["bash", "-c", "export DOTNET_CLI_TELEMETRY_OPTOUT=1; cd /app && dotnet restore && dotnet publish -c Release -o publish"]

